language: python

python:
  - 3.6

install: "pip install -r requirements.txt"

script: make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $mytoken2
  local_dir: build/html/
  on:
    branch: master